version: "3.7"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: mysql-prepared-conn-test
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
    ports:
    - target: 3306
      published: 3306
      protocol: tcp

volumes:
  mysql-data:
  mysql-logs:
